### ISSUE TITLE
运行libri语料库出错

### ISSUE THREAD

**Issue by SunQinyao** [zzw922cn/Automatic_Speech_Recognition#21]
您好！
	我在运行您github上的代码时，已经运行成功了libri_preprocess.py，然后再运行训练的代码出现了一个错误，如下所示：
[gpu3@localhost main]$ python libri_train.py
Initializing
Epoch 1 ...
Traceback (most recent call last):
  File "libri_train.py", line 281, in <module>
    runner.run()
  File "libri_train.py", line 216, in run
    feed_dict=feedDict)
  File "/home/gpu3/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/gpu3/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 961, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1731, 64, 39) for Tensor u'Placeholder:0', which has shape '(1731, 64, 60)
麻烦问一下这个怎么解决呢？

**Comment by zzw922cn** [comment]
@SunQinyao 你好，出错的原因是你预处理的特征长度为39,而在libri train中设置的可能是60？二者不一致导致的

**Comment by filmonhg** [comment]
I solved this issue by changing the default num_feature to 39 in your libri_train
