### ISSUE TITLE
ImportError: No module named dynamic_brnn

### ISSUE THREAD

**Issue by liuyanliangm** [zzw922cn/Automatic_Speech_Recognition#32]
(conASR) lyl@lyldm:~/lylgit/Automatic_Speech_Recognition/main$ python timit_train.py -h
Traceback (most recent call last):
  File "timit_train.py", line 39, in <module>
    from utils.functionDictUtils import model_functions_dict
  File "../utils/functionDictUtils.py", line 17, in <module>
    from models.dynamic_brnn import DBiRNN
ImportError: No module named dynamic_brnn

**Comment by liuyanliangm** [comment]
![2017-09-08 23-17-05](https://user-images.githubusercontent.com/24785652/30200504-cc546d86-94a9-11e7-9e3f-13ee36f588dd.png)

**Comment by liuyanliangm** [comment]
I don't know why 。And  i already put "Automatic_Speech_Recognition" path in sys.path

**Comment by zzw922cn** [comment]
@liuyanliangm hi, i also don't know why you met this error. Sorry.

**Comment by holianh** [comment]
I also face this error :(

**Comment by AmirLavasani** [comment]
you are calling timit_train.py inside the main folder and model folder is one directory top so python can not solve the models path. 
run it from the repo directory: python main/timit_train.py 
I did it this way and it worked.
