### ISSUE TITLE
Problem with DeepSpeech2

### ISSUE THREAD

**Issue by fanlamda** [zzw922cn/Automatic_Speech_Recognition#79]
I have an error when running with the DeepSpeech2 model. Any idea with this problem is welcome. I have tried tensorflow version 1.1-1.4. All failed
Traceback (most recent call last):
  File "libri_train.py", line 265, in <module>
    runner.run()
  File "libri_train.py", line 152, in run
    model = model_fn(args, maxTimeSteps)
  File "build/bdist.linux-x86_64/egg/speechvalley/models/deepSpeech2.py", line 105, in __init__
  File "build/bdist.linux-x86_64/egg/speechvalley/utils/utils.py", line 25, in wrapper
  File "build/bdist.linux-x86_64/egg/speechvalley/models/deepSpeech2.py", line 134, in build_graph
  File "build/bdist.linux-x86_64/egg/speechvalley/models/deepSpeech2.py", line 44, in build_deepSpeech2
  File "/home/fanlei1/anaconda2/lib/python2.7/site-packages/tensorflow/python/layers/normalization.py", line 586, in batch_normalization
    return layer.apply(inputs, training=training)
  File "/home/fanl/anaconda2/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 671, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/fanl/anaconda2/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/fanl/anaconda2/lib/python2.7/site-packages/tensorflow/python/layers/normalization.py", line 395, in call
    return self._fused_batch_norm(inputs, training=training)
  File "/home/fanl/anaconda2/lib/python2.7/site-packages/tensorflow/python/layers/normalization.py", line 302, in _fused_batch_norm
    training, _fused_batch_norm_training, _fused_batch_norm_inference)
  File "/home/fanl/anaconda2/lib/python2.7/site-packages/tensorflow/python/layers/utils.py", line 203, in smart_cond
    pred_value = constant_value(pred)
  File "/home/fanl/anaconda2/lib/python2.7/site-packages/tensorflow/python/layers/utils.py", line 233, in constant_value
    raise TypeError('`pred` must be a Tensor, a Variable, or a Python bool.')
TypeError: `pred` must be a Tensor, a Variable, or a Python bool.

**Comment by michaelklachko** [comment]
DeepSpeech2 model appears to be broken. Your particular error just means that the argument isTraining is not supplied (because it does not exist). But even if you fix this error, there will be plenty more...
