### ISSUE TITLE
Weird error during preprocessing

### ISSUE THREAD

**Issue by michaelklachko** [zzw922cn/Automatic_Speech_Recognition#81]
Hi, I'm trying to process LibriSpeech dataset, after following installation instructions exactly: 

```
(asr) michael@Pascal:~/Automatic_Speech_Recognition/speechvalley/feature/libri$ python libri_preprocess.py ~/deepSpeech2/data/LibriSpeech/audio/train-clean-100 processed_data
Traceback (most recent call last):
  File "libri_preprocess.py", line 18, in <module>
    from speechvalley.feature.core import calcfeat_delta_delta
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/michael/miniconda2/envs/asr/lib/python3.5/site-packages/SpeechValley-1.0.0-py3.5.egg/speechvalley/feature/__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/michael/miniconda2/envs/asr/lib/python3.5/site-packages/SpeechValley-1.0.0-py3.5.egg/speechvalley/feature/wsj/__init__.py", line 10, in <module>
    from speechvalley.feature.libri.libri_preprocess import preprocess, wav2feature
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1171, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1147, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1128, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 565, in spec_from_file_location
  File "/home/michael/miniconda2/envs/asr/lib/python3.5/site-packages/SpeechValley-1.0.0-py3.5.egg/speechvalley/feature/wsj/extract_wsj.py", line 20
    print f
          ^
SyntaxError: Missing parentheses in call to 'print'
```

I'm not quite sure what's going on, or why it's trying to access extract_wsj.py code. Should I convert that file to python3 immediately after cloning the repo (before running setup.py script)? Is there a way to use the code without installing it with setup? I'm not very familiar with how the python egg files work...

**Comment by michaelklachko** [comment]
After encountering a whole bunch of issues with the code, I had to copy all the functions into 3 files in the same folder, and then ran train function without installing anything. Still had to correct a lot of minor errors. It seems like libri_train.py was not tested at all.
